# Generated by Django 3.2.4 on 2021-06-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210616_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='release_date',
            new_name='date',
        ),
    ]
