# Generated by Django 3.2.4 on 2021-06-16 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_release_date_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='state',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='zip',
        ),
        migrations.AddField(
            model_name='contact',
            name='desc',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
